### ISSUE TITLE
Create Skeleton

### ISSUE THREAD

**Issue by immanuelqrw** [immanuelqrw/Anubis#16]
### Description
Create Skeleton React website without functionality

### Details
Need to create skeleton website before features can be plugged in

### Acceptance Criteria
- Project reachable through GitHub pages endpoint
- anubis.iqrw.dev hostname
- Basic webpage for viewing a table
- Basic webpage for inserting data

### Tasks
- [ ] Create github pages branch
- [ ] Make page accessible through custom hostname
- [ ] Implement view component
- [ ] Implement data insert component
